version: 0.2
phases:
 pre_build:
  commands:
  - echo "hello-me-comments"
 build:
  commands:
  - echo "build phase"
  - mvn clean package
 post_build:
  commands:
  - echo "post build phase"
  - mv target/*.jar demoJava.jar
artifacts:
 files:
  - demoJava.jar