apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoJava-app
  labels:
    app: demoJava-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoJava-app
  template:
    metadata:
      labels:
        app: demoJava-app
    spec:
      containers:
        - name: demoJava-app
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demoJava-svc
spec:
  ports:
    - targetPort: 8080
      port: 80
  selector:
    app: demoJava-app
